### ISSUE TITLE
Missing `s6-applyuidgid`

### ISSUE THREAD

**Issue by felipecrs** [hassio-addons/addon-base-python#102]
```console
$ docker run --rm -it --entrypoint= ghcr.io/hassio-addons/base/amd64:11.0.1 stat /bin/s6-applyuidgid
  File: /bin/s6-applyuidgid
  Size: 17320           Blocks: 40         IO Block: 4096   regular file
Device: 43h/67d Inode: 75235       Links: 1
Access: (0700/-rwx------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-01-22 13:36:36.000000000 +0000
Modify: 2021-01-22 13:36:36.000000000 +0000
Change: 2022-02-08 14:42:52.248227189 +0000

$ docker run --rm -it --entrypoint= ghcr.io/hassio-addons/base-python/amd64:8.0.1 stat /bin/s6-applyuidgid
stat: can't stat '/bin/s6-applyuidgid': No such file or directory
```

Refs https://github.com/TECH7Fox/Asterisk-add-on/pull/92#discussion_r803015761

**Comment by felipecrs** [comment]
For some reason, this image removes the file:

https://user-images.githubusercontent.com/29582865/153282393-4973a503-1a85-442a-8f98-de4d83ae7d26.mp4

**Comment by felipecrs** [comment]
This issue seems to be introduced by `apk add coreutils`. This command modifies the permission of the given file, and because of that, it gets removed later in `apk del --purge`.

**Comment by felipecrs** [comment]
@frenck I don't want to disturb, but if a new patch version could be released to include this fix, it would be super appreciated.

**Comment by frenck** [comment]
Working on adding some other things to the base at this point, so, soon™

**Comment by felipecrs** [comment]
Nice, thanks!
