### ISSUE TITLE
Compatibility with alpine py3-* packages

### ISSUE THREAD

**Issue by NigelRook** [hassio-addons/addon-base-python#2]
# Problem/Motivation

`apk install py3-*` inside this container installs python modules for python 3.6, while python in this container is version 3.7, meaning the installed modules are unavailable.

Required packages can be installed through pip, but for some binary python packages (in my case numpy and scipy) this is very time consuming. Given that hassio recreates the container every restart, this is particularly problematic.

See https://github.com/hassio-addons/addon-appdaemon3/issues/43

## Expected behavior

```
apk install py3-numpy
python
>>> import numpy
```

Is successful

## Actual behavior

`import numpy` results in a `ModuleNotFoundError`

## Proposed changes

Given alpine edge repositories are already available in the container, using a fixed python 3.7 package from there instead of building locally may work. The edge package of python 3.7 requires a newer version of readline (8.x vs 7.x) than the alpine 3.9 version of bash, so either bash would need upgrading too, or apk would need to be coerced into installing both versions of readline.

Or something else :)

**Comment by frenck** [comment]
That is not going to happen and/or work, since Alpine is on Python 3.6.
